// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_users_upload_avatarSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_users-upload_avatar'
} as const;

export const CategoriesAdminSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryAdmin'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesAdmin'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic'
} as const;

export const CategoryAdminSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        in_use: {
            type: 'boolean',
            title: 'In Use',
            default: false
        },
        resources_count: {
            type: 'integer',
            title: 'Resources Count',
            default: 0
        },
        submissions_count: {
            type: 'integer',
            title: 'Submissions Count',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'CategoryAdmin'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'CategoryPublic'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryUpdate'
} as const;

export const ChatMessageSchemaSchema = {
    properties: {
        role: {
            type: 'string',
            maxLength: 20,
            title: 'Role'
        },
        content: {
            type: 'string',
            maxLength: 4000,
            minLength: 1,
            title: 'Content'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['role', 'content'],
    title: 'ChatMessageSchema',
    description: 'Schema for a single chat message in a transcript.'
} as const;

export const ChatTranscriptCreateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        messages: {
            items: {
                '$ref': '#/components/schemas/ChatMessageSchema'
            },
            type: 'array',
            minItems: 1,
            title: 'Messages'
        }
    },
    type: 'object',
    required: ['messages'],
    title: 'ChatTranscriptCreate',
    description: 'Request body for saving a chat transcript.'
} as const;

export const ChatTranscriptPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        messages: {
            items: {
                '$ref': '#/components/schemas/ChatMessageSchema'
            },
            type: 'array',
            title: 'Messages'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'messages', 'created_at', 'updated_at'],
    title: 'ChatTranscriptPublic',
    description: 'Response schema for a saved chat transcript.'
} as const;

export const ChatTranscriptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChatTranscriptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChatTranscriptsPublic',
    description: 'Paginated list of saved chat transcripts.'
} as const;

export const CommentCreateSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Body'
        }
    },
    type: 'object',
    required: ['body'],
    title: 'CommentCreate'
} as const;

export const CommentPublicSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Body'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        author_id: {
            type: 'string',
            format: 'uuid',
            title: 'Author Id'
        },
        author_display: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Display'
        },
        resource_id: {
            type: 'string',
            format: 'uuid',
            title: 'Resource Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['body', 'id', 'author_id', 'resource_id', 'created_at', 'updated_at'],
    title: 'CommentPublic'
} as const;

export const CommentUpdateSchema = {
    properties: {
        body: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        }
    },
    type: 'object',
    title: 'CommentUpdate'
} as const;

export const CommentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CommentsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LandingChatRequestSchema = {
    properties: {
        message: {
            type: 'string',
            maxLength: 4000,
            minLength: 1,
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'LandingChatRequest',
    description: 'Request body for landing chat recommendations.'
} as const;

export const LandingChatResponseSchema = {
    properties: {
        assistant_message: {
            type: 'string',
            title: 'Assistant Message'
        },
        recommendations: {
            items: {
                '$ref': '#/components/schemas/ResourcePreview'
            },
            type: 'array',
            title: 'Recommendations'
        }
    },
    type: 'object',
    required: ['assistant_message', 'recommendations'],
    title: 'LandingChatResponse',
    description: 'Response from landing chat recommendations endpoint.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReactionStateSchema = {
    properties: {
        active: {
            type: 'boolean',
            title: 'Active'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['active', 'count'],
    title: 'ReactionState'
} as const;

export const ResourceCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        destination_url: {
            type: 'string',
            maxLength: 2048,
            title: 'Destination Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    required: ['title', 'destination_url'],
    title: 'ResourceCreate'
} as const;

export const ResourceDetailPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        destination_url: {
            type: 'string',
            title: 'Destination Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        category_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Name'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published'
        },
        published_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published By Id'
        },
        published_by_display: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published By Display'
        },
        published_by_avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published By Avatar Url'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        likes_count: {
            type: 'integer',
            title: 'Likes Count',
            default: 0
        },
        favorites_count: {
            type: 'integer',
            title: 'Favorites Count',
            default: 0
        },
        liked_by_me: {
            type: 'boolean',
            title: 'Liked By Me',
            default: false
        },
        favorited_by_me: {
            type: 'boolean',
            title: 'Favorited By Me',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'title', 'destination_url', 'is_published', 'created_at', 'updated_at'],
    title: 'ResourceDetailPublic'
} as const;

export const ResourcePreviewSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        category_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Name'
        }
    },
    type: 'object',
    required: ['id', 'title', 'description'],
    title: 'ResourcePreview',
    description: 'Compact resource summary for chat recommendations.'
} as const;

export const ResourcePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        destination_url: {
            type: 'string',
            title: 'Destination Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        category_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Name'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published'
        },
        published_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published By Id'
        },
        published_by_display: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published By Display'
        },
        published_by_avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published By Avatar Url'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'destination_url', 'is_published', 'created_at', 'updated_at'],
    title: 'ResourcePublic'
} as const;

export const ResourceSubmissionCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        destination_url: {
            type: 'string',
            maxLength: 2048,
            title: 'Destination Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    required: ['title', 'destination_url'],
    title: 'ResourceSubmissionCreate'
} as const;

export const ResourceSubmissionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        destination_url: {
            type: 'string',
            title: 'Destination Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        category_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        submitter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Submitter Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'destination_url', 'status', 'submitter_id', 'created_at', 'updated_at'],
    title: 'ResourceSubmissionPublic'
} as const;

export const ResourceSubmissionUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        destination_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Destination Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    title: 'ResourceSubmissionUpdate'
} as const;

export const ResourceSubmissionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ResourceSubmissionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ResourceSubmissionsPublic'
} as const;

export const ResourceUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        destination_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Destination Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        is_published: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Published'
        }
    },
    type: 'object',
    title: 'ResourceUpdate'
} as const;

export const ResourcesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ResourcePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ResourcesPublic'
} as const;

export const SubmissionCommentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        author_id: {
            type: 'string',
            format: 'uuid',
            title: 'Author Id'
        },
        author_display: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Display'
        },
        submission_id: {
            type: 'string',
            format: 'uuid',
            title: 'Submission Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'body', 'author_id', 'submission_id', 'created_at', 'updated_at'],
    title: 'SubmissionCommentPublic'
} as const;

export const SubmissionCommentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SubmissionCommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SubmissionCommentsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        locale: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['en', 'zh']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Locale'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        avatar_version: {
            type: 'integer',
            title: 'Avatar Version',
            default: 0
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        locale: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['en', 'zh']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Locale'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WeChatAccountLinkPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        openid: {
            type: 'string',
            title: 'Openid'
        },
        unionid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unionid'
        },
        nickname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nickname'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'openid', 'unionid', 'nickname', 'avatar_url', 'created_at'],
    title: 'WeChatAccountLinkPublic',
    description: 'Public representation of WeChat account link.'
} as const;

export const WeChatLinkRequestSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Code'
        },
        state: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'State'
        }
    },
    type: 'object',
    required: ['code', 'state'],
    title: 'WeChatLinkRequest',
    description: 'Request body for linking WeChat to current user.'
} as const;

export const WeChatLoginCompleteRequestSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Code'
        },
        state: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'State'
        }
    },
    type: 'object',
    required: ['code', 'state'],
    title: 'WeChatLoginCompleteRequest',
    description: 'Request body for completing WeChat login.'
} as const;

export const WeChatLoginStartRequestSchema = {
    properties: {
        return_to: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Return To'
        }
    },
    type: 'object',
    title: 'WeChatLoginStartRequest',
    description: 'Request body for starting WeChat login.'
} as const;

export const WeChatLoginStartResponseSchema = {
    properties: {
        appid: {
            type: 'string',
            title: 'Appid'
        },
        scope: {
            type: 'string',
            title: 'Scope'
        },
        redirect_uri: {
            type: 'string',
            title: 'Redirect Uri'
        },
        state: {
            type: 'string',
            title: 'State'
        },
        wx_login_js_url: {
            type: 'string',
            title: 'Wx Login Js Url',
            default: 'https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js'
        }
    },
    type: 'object',
    required: ['appid', 'scope', 'redirect_uri', 'state'],
    title: 'WeChatLoginStartResponse',
    description: 'Response with parameters to render embedded WeChat QR.'
} as const;