// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Schema for a single chat message in a transcript.
 */
export type ChatMessageSchema = {
    role: string;
    content: string;
    created_at?: (string | null);
};

/**
 * Request body for saving a chat transcript.
 */
export type ChatTranscriptCreate = {
    title?: (string | null);
    messages: Array<ChatMessageSchema>;
};

/**
 * Response schema for a saved chat transcript.
 */
export type ChatTranscriptPublic = {
    id: string;
    title: (string | null);
    messages: Array<ChatMessageSchema>;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated list of saved chat transcripts.
 */
export type ChatTranscriptsPublic = {
    data: Array<ChatTranscriptPublic>;
    count: number;
};

export type CommentCreate = {
    body: string;
};

export type CommentPublic = {
    body: string;
    id: string;
    author_id: string;
    author_display?: (string | null);
    resource_id: string;
    created_at: string;
    updated_at: string;
};

export type CommentsPublic = {
    data: Array<CommentPublic>;
    count: number;
};

export type CommentUpdate = {
    body?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Request body for landing chat recommendations.
 */
export type LandingChatRequest = {
    message: string;
};

/**
 * Response from landing chat recommendations endpoint.
 */
export type LandingChatResponse = {
    assistant_message: string;
    recommendations: Array<ResourcePreview>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReactionState = {
    active: boolean;
    count: number;
};

export type ResourceCreate = {
    title: string;
    description?: (string | null);
    destination_url: string;
    type: string;
};

export type ResourceDetailPublic = {
    title: string;
    description?: (string | null);
    destination_url: string;
    type: string;
    id: string;
    is_published: boolean;
    published_by_id?: (string | null);
    published_by_display?: (string | null);
    created_at: string;
    updated_at: string;
    likes_count?: number;
    favorites_count?: number;
    liked_by_me?: boolean;
    favorited_by_me?: boolean;
};

/**
 * Compact resource summary for chat recommendations.
 */
export type ResourcePreview = {
    id: string;
    title: string;
    description: (string | null);
    type: string;
};

export type ResourcePublic = {
    title: string;
    description?: (string | null);
    destination_url: string;
    type: string;
    id: string;
    is_published: boolean;
    published_by_id?: (string | null);
    published_by_display?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ResourcesPublic = {
    data: Array<ResourcePublic>;
    count: number;
};

export type ResourceSubmissionCreate = {
    title: string;
    description?: (string | null);
    destination_url: string;
    type: string;
};

export type ResourceSubmissionPublic = {
    title: string;
    description?: (string | null);
    destination_url: string;
    type: string;
    id: string;
    status: string;
    submitter_id: string;
    created_at: string;
    updated_at: string;
};

export type ResourceSubmissionsPublic = {
    data: Array<ResourceSubmissionPublic>;
    count: number;
};

export type ResourceSubmissionUpdate = {
    title?: (string | null);
    description?: (string | null);
    destination_url?: (string | null);
    type?: (string | null);
};

export type ResourceUpdate = {
    title?: (string | null);
    description?: (string | null);
    destination_url?: (string | null);
    type?: (string | null);
    is_published?: (boolean | null);
};

export type SubmissionCommentPublic = {
    id: string;
    body: string;
    author_id: string;
    author_display?: (string | null);
    submission_id: string;
    created_at: string;
    updated_at: string;
};

export type SubmissionCommentsPublic = {
    data: Array<SubmissionCommentPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    locale?: ('en' | 'zh' | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    locale?: ('en' | 'zh' | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ChatTranscriptsListMyTranscriptsData = {
    limit?: number;
    skip?: number;
};

export type ChatTranscriptsListMyTranscriptsResponse = (ChatTranscriptsPublic);

export type ChatTranscriptsSaveTranscriptData = {
    requestBody: ChatTranscriptCreate;
};

export type ChatTranscriptsSaveTranscriptResponse = (ChatTranscriptPublic);

export type ChatTranscriptsGetMyTranscriptData = {
    id: string;
};

export type ChatTranscriptsGetMyTranscriptResponse = (ChatTranscriptPublic);

export type ChatTranscriptsDeleteMyTranscriptData = {
    id: string;
};

export type ChatTranscriptsDeleteMyTranscriptResponse = (Message);

export type CommentsUpdateCommentData = {
    id: string;
    requestBody: CommentUpdate;
};

export type CommentsUpdateCommentResponse = (CommentPublic);

export type CommentsDeleteCommentData = {
    id: string;
};

export type CommentsDeleteCommentResponse = (Message);

export type CommentsUpdateSubmissionCommentData = {
    id: string;
    requestBody: CommentUpdate;
};

export type CommentsUpdateSubmissionCommentResponse = (SubmissionCommentPublic);

export type CommentsDeleteSubmissionCommentData = {
    id: string;
};

export type CommentsDeleteSubmissionCommentResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LandingChatRecommendResourcesData = {
    requestBody: LandingChatRequest;
};

export type LandingChatRecommendResourcesResponse = (LandingChatResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ResourcesListResourcesData = {
    isPublished?: (boolean | null);
    limit?: number;
    q?: (string | null);
    skip?: number;
    type?: (string | null);
};

export type ResourcesListResourcesResponse = (ResourcesPublic);

export type ResourcesCreateResourceData = {
    requestBody: ResourceCreate;
};

export type ResourcesCreateResourceResponse = (ResourcePublic);

export type ResourcesGetResourceData = {
    id: string;
};

export type ResourcesGetResourceResponse = (ResourceDetailPublic);

export type ResourcesUpdateResourceData = {
    id: string;
    requestBody: ResourceUpdate;
};

export type ResourcesUpdateResourceResponse = (ResourcePublic);

export type ResourcesDeleteResourceData = {
    id: string;
};

export type ResourcesDeleteResourceResponse = (Message);

export type ResourcesLikeResourceData = {
    id: string;
};

export type ResourcesLikeResourceResponse = (ReactionState);

export type ResourcesUnlikeResourceData = {
    id: string;
};

export type ResourcesUnlikeResourceResponse = (ReactionState);

export type ResourcesFavoriteResourceData = {
    id: string;
};

export type ResourcesFavoriteResourceResponse = (ReactionState);

export type ResourcesUnfavoriteResourceData = {
    id: string;
};

export type ResourcesUnfavoriteResourceResponse = (ReactionState);

export type ResourcesListMyFavoritesData = {
    limit?: number;
    skip?: number;
};

export type ResourcesListMyFavoritesResponse = (ResourcesPublic);

export type ResourcesListResourceCommentsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type ResourcesListResourceCommentsResponse = (CommentsPublic);

export type ResourcesCreateResourceCommentData = {
    id: string;
    requestBody: CommentCreate;
};

export type ResourcesCreateResourceCommentResponse = (CommentPublic);

export type SubmissionsListMySubmissionsData = {
    limit?: number;
    skip?: number;
};

export type SubmissionsListMySubmissionsResponse = (ResourceSubmissionsPublic);

export type SubmissionsCreateSubmissionData = {
    requestBody: ResourceSubmissionCreate;
};

export type SubmissionsCreateSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsListPendingSubmissionsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type SubmissionsListPendingSubmissionsResponse = (ResourceSubmissionsPublic);

export type SubmissionsGetSubmissionData = {
    id: string;
};

export type SubmissionsGetSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsUpdateSubmissionData = {
    id: string;
    requestBody: ResourceSubmissionUpdate;
};

export type SubmissionsUpdateSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsDeleteSubmissionData = {
    id: string;
};

export type SubmissionsDeleteSubmissionResponse = (Message);

export type SubmissionsApproveSubmissionData = {
    id: string;
};

export type SubmissionsApproveSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsRejectSubmissionData = {
    id: string;
};

export type SubmissionsRejectSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsListSubmissionCommentsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type SubmissionsListSubmissionCommentsResponse = (SubmissionCommentsPublic);

export type SubmissionsCreateSubmissionCommentData = {
    id: string;
    requestBody: CommentCreate;
};

export type SubmissionsCreateSubmissionCommentResponse = (SubmissionCommentPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);