// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_resources_upload_resource_image = {
    file: (Blob | File);
};

export type Body_submissions_upload_submission_image = {
    file: (Blob | File);
};

export type Body_users_upload_avatar = {
    file: (Blob | File);
};

export type CategoriesAdmin = {
    data: Array<CategoryAdmin>;
    count: number;
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryAdmin = {
    name: string;
    id: string;
    in_use?: boolean;
    resources_count?: number;
    submissions_count?: number;
};

export type CategoryCreate = {
    name: string;
};

export type CategoryPublic = {
    name: string;
    id: string;
};

export type CategoryUpdate = {
    name: string;
};

/**
 * Schema for a single chat message in a transcript.
 */
export type ChatMessageSchema = {
    role: string;
    content: string;
    created_at?: (string | null);
};

/**
 * Request body for saving a chat transcript.
 */
export type ChatTranscriptCreate = {
    title?: (string | null);
    messages: Array<ChatMessageSchema>;
};

/**
 * Response schema for a saved chat transcript.
 */
export type ChatTranscriptPublic = {
    id: string;
    title: (string | null);
    messages: Array<ChatMessageSchema>;
    created_at: string;
    updated_at: string;
};

/**
 * Paginated list of saved chat transcripts.
 */
export type ChatTranscriptsPublic = {
    data: Array<ChatTranscriptPublic>;
    count: number;
};

export type CommentCreate = {
    body: string;
};

export type CommentPublic = {
    body: string;
    id: string;
    author_id: string;
    author_display?: (string | null);
    resource_id: string;
    created_at: string;
    updated_at: string;
};

export type CommentsPublic = {
    data: Array<CommentPublic>;
    count: number;
};

export type CommentUpdate = {
    body?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Request body for landing chat recommendations.
 */
export type LandingChatRequest = {
    message: string;
};

/**
 * Response from landing chat recommendations endpoint.
 */
export type LandingChatResponse = {
    assistant_message: string;
    recommendations: Array<ResourcePreview>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReactionState = {
    active: boolean;
    count: number;
};

export type ResourceCreate = {
    title: string;
    description?: (string | null);
    destination_url: string;
    category_id?: (string | null);
    image_external_url?: (string | null);
};

export type ResourceDetailPublic = {
    id: string;
    title: string;
    description?: (string | null);
    destination_url: string;
    category_id?: (string | null);
    category_name?: (string | null);
    is_published: boolean;
    published_by_id?: (string | null);
    published_by_display?: (string | null);
    published_by_avatar_url?: (string | null);
    created_at: string;
    updated_at: string;
    likes_count?: number;
    image_url?: (string | null);
    favorites_count?: number;
    liked_by_me?: boolean;
    favorited_by_me?: boolean;
};

/**
 * Compact resource summary for chat recommendations.
 */
export type ResourcePreview = {
    id: string;
    title: string;
    description: (string | null);
    category_id?: (string | null);
    category_name?: (string | null);
};

export type ResourcePublic = {
    id: string;
    title: string;
    description?: (string | null);
    destination_url: string;
    category_id?: (string | null);
    category_name?: (string | null);
    is_published: boolean;
    published_by_id?: (string | null);
    published_by_display?: (string | null);
    published_by_avatar_url?: (string | null);
    created_at: string;
    updated_at: string;
    likes_count?: number;
    image_url?: (string | null);
};

export type ResourcesPublic = {
    data: Array<ResourcePublic>;
    count: number;
};

export type ResourceSubmissionCreate = {
    title: string;
    description?: (string | null);
    destination_url: string;
    category_id?: (string | null);
    image_external_url?: (string | null);
};

export type ResourceSubmissionPublic = {
    id: string;
    title: string;
    description?: (string | null);
    destination_url: string;
    category_id?: (string | null);
    category_name?: (string | null);
    status: string;
    submitter_id: string;
    created_at: string;
    updated_at: string;
    image_url?: (string | null);
};

export type ResourceSubmissionsPublic = {
    data: Array<ResourceSubmissionPublic>;
    count: number;
};

export type ResourceSubmissionUpdate = {
    title?: (string | null);
    description?: (string | null);
    destination_url?: (string | null);
    category_id?: (string | null);
    image_external_url?: (string | null);
};

export type ResourceUpdate = {
    title?: (string | null);
    description?: (string | null);
    destination_url?: (string | null);
    category_id?: (string | null);
    is_published?: (boolean | null);
    image_external_url?: (string | null);
};

export type SubmissionCommentPublic = {
    id: string;
    body: string;
    author_id: string;
    author_display?: (string | null);
    submission_id: string;
    created_at: string;
    updated_at: string;
};

export type SubmissionCommentsPublic = {
    data: Array<SubmissionCommentPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    locale?: ('en' | 'zh' | null);
    avatar_url?: (string | null);
    avatar_version?: number;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    locale?: ('en' | 'zh' | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Public representation of WeChat account link.
 */
export type WeChatAccountLinkPublic = {
    id: string;
    openid: string;
    unionid: (string | null);
    nickname: (string | null);
    avatar_url: (string | null);
    created_at: string;
};

/**
 * Request body for linking WeChat to current user.
 */
export type WeChatLinkRequest = {
    code: string;
    state: string;
};

/**
 * Request body for completing WeChat login.
 */
export type WeChatLoginCompleteRequest = {
    code: string;
    state: string;
};

/**
 * Request body for starting WeChat login.
 */
export type WeChatLoginStartRequest = {
    return_to?: (string | null);
};

/**
 * Response with parameters to render embedded WeChat QR.
 */
export type WeChatLoginStartResponse = {
    appid: string;
    scope: string;
    redirect_uri: string;
    state: string;
    wx_login_js_url?: string;
};

export type AvatarsGetAvatarData = {
    /**
     * File extension
     */
    ext: string;
    /**
     * User ID
     */
    userId: string;
    /**
     * Avatar version
     */
    version: number;
};

export type AvatarsGetAvatarResponse = (unknown);

export type CategoriesListCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesListCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesListCategoriesAdminData = {
    limit?: number;
    skip?: number;
};

export type CategoriesListCategoriesAdminResponse = (CategoriesAdmin);

export type CategoriesUpdateCategoryData = {
    id: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    id: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type ChatTranscriptsListMyTranscriptsData = {
    limit?: number;
    skip?: number;
};

export type ChatTranscriptsListMyTranscriptsResponse = (ChatTranscriptsPublic);

export type ChatTranscriptsSaveTranscriptData = {
    requestBody: ChatTranscriptCreate;
};

export type ChatTranscriptsSaveTranscriptResponse = (ChatTranscriptPublic);

export type ChatTranscriptsGetMyTranscriptData = {
    id: string;
};

export type ChatTranscriptsGetMyTranscriptResponse = (ChatTranscriptPublic);

export type ChatTranscriptsDeleteMyTranscriptData = {
    id: string;
};

export type ChatTranscriptsDeleteMyTranscriptResponse = (Message);

export type CommentsUpdateCommentData = {
    id: string;
    requestBody: CommentUpdate;
};

export type CommentsUpdateCommentResponse = (CommentPublic);

export type CommentsDeleteCommentData = {
    id: string;
};

export type CommentsDeleteCommentResponse = (Message);

export type CommentsUpdateSubmissionCommentData = {
    id: string;
    requestBody: CommentUpdate;
};

export type CommentsUpdateSubmissionCommentResponse = (SubmissionCommentPublic);

export type CommentsDeleteSubmissionCommentData = {
    id: string;
};

export type CommentsDeleteSubmissionCommentResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LandingChatRecommendResourcesData = {
    requestBody: LandingChatRequest;
};

export type LandingChatRecommendResourcesResponse = (LandingChatResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ResourceImagesServeResourceImageData = {
    ext: string;
    resourceId: string;
    version: number;
};

export type ResourceImagesServeResourceImageResponse = (unknown);

export type ResourcesListResourcesData = {
    categoryId?: (string | null);
    isPublished?: (boolean | null);
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type ResourcesListResourcesResponse = (ResourcesPublic);

export type ResourcesCreateResourceData = {
    requestBody: ResourceCreate;
};

export type ResourcesCreateResourceResponse = (ResourcePublic);

export type ResourcesGetResourceData = {
    id: string;
};

export type ResourcesGetResourceResponse = (ResourceDetailPublic);

export type ResourcesUpdateResourceData = {
    id: string;
    requestBody: ResourceUpdate;
};

export type ResourcesUpdateResourceResponse = (ResourcePublic);

export type ResourcesDeleteResourceData = {
    id: string;
};

export type ResourcesDeleteResourceResponse = (Message);

export type ResourcesUploadResourceImageData = {
    formData: Body_resources_upload_resource_image;
    id: string;
};

export type ResourcesUploadResourceImageResponse = (ResourcePublic);

export type ResourcesClearResourceImageData = {
    id: string;
};

export type ResourcesClearResourceImageResponse = (ResourcePublic);

export type ResourcesLikeResourceData = {
    id: string;
};

export type ResourcesLikeResourceResponse = (ReactionState);

export type ResourcesUnlikeResourceData = {
    id: string;
};

export type ResourcesUnlikeResourceResponse = (ReactionState);

export type ResourcesFavoriteResourceData = {
    id: string;
};

export type ResourcesFavoriteResourceResponse = (ReactionState);

export type ResourcesUnfavoriteResourceData = {
    id: string;
};

export type ResourcesUnfavoriteResourceResponse = (ReactionState);

export type ResourcesListMyFavoritesData = {
    limit?: number;
    skip?: number;
};

export type ResourcesListMyFavoritesResponse = (ResourcesPublic);

export type ResourcesListResourceCommentsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type ResourcesListResourceCommentsResponse = (CommentsPublic);

export type ResourcesCreateResourceCommentData = {
    id: string;
    requestBody: CommentCreate;
};

export type ResourcesCreateResourceCommentResponse = (CommentPublic);

export type SubmissionImagesGetSubmissionImageData = {
    submissionId: string;
    /**
     * Image version for cache busting
     */
    v?: number;
};

export type SubmissionImagesGetSubmissionImageResponse = (unknown);

export type SubmissionsListMySubmissionsData = {
    limit?: number;
    skip?: number;
};

export type SubmissionsListMySubmissionsResponse = (ResourceSubmissionsPublic);

export type SubmissionsCreateSubmissionData = {
    requestBody: ResourceSubmissionCreate;
};

export type SubmissionsCreateSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsListPendingSubmissionsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type SubmissionsListPendingSubmissionsResponse = (ResourceSubmissionsPublic);

export type SubmissionsGetSubmissionData = {
    id: string;
};

export type SubmissionsGetSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsUpdateSubmissionData = {
    id: string;
    requestBody: ResourceSubmissionUpdate;
};

export type SubmissionsUpdateSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsDeleteSubmissionData = {
    id: string;
};

export type SubmissionsDeleteSubmissionResponse = (Message);

export type SubmissionsUploadSubmissionImageData = {
    formData: Body_submissions_upload_submission_image;
    id: string;
};

export type SubmissionsUploadSubmissionImageResponse = (ResourceSubmissionPublic);

export type SubmissionsClearSubmissionImageData = {
    id: string;
};

export type SubmissionsClearSubmissionImageResponse = (ResourceSubmissionPublic);

export type SubmissionsApproveSubmissionData = {
    id: string;
};

export type SubmissionsApproveSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsRejectSubmissionData = {
    id: string;
};

export type SubmissionsRejectSubmissionResponse = (ResourceSubmissionPublic);

export type SubmissionsListSubmissionCommentsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type SubmissionsListSubmissionCommentsResponse = (SubmissionCommentsPublic);

export type SubmissionsCreateSubmissionCommentData = {
    id: string;
    requestBody: CommentCreate;
};

export type SubmissionsCreateSubmissionCommentResponse = (SubmissionCommentPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUploadAvatarData = {
    formData: Body_users_upload_avatar;
};

export type UsersUploadAvatarResponse = (UserPublic);

export type UsersDeleteAvatarResponse = (UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WechatLoginWechatLoginStartData = {
    requestBody?: (WeChatLoginStartRequest | null);
};

export type WechatLoginWechatLoginStartResponse = (WeChatLoginStartResponse);

export type WechatLoginWechatLoginCompleteData = {
    requestBody: WeChatLoginCompleteRequest;
};

export type WechatLoginWechatLoginCompleteResponse = (Token);

export type WechatLoginWechatLinkStatusResponse = ((WeChatAccountLinkPublic | null));

export type WechatLoginWechatLinkData = {
    requestBody: WeChatLinkRequest;
};

export type WechatLoginWechatLinkResponse = (Message);

export type WechatLoginWechatUnlinkResponse = (Message);