/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WechatCallbackRouteImport } from './routes/wechat-callback'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFavoritesRouteImport } from './routes/_layout/favorites'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSubmissionsIndexRouteImport } from './routes/_layout/submissions/index'
import { Route as LayoutResourcesIndexRouteImport } from './routes/_layout/resources/index'
import { Route as LayoutSubmissionsNewRouteImport } from './routes/_layout/submissions/new'
import { Route as LayoutSubmissionsSubmissionIdRouteImport } from './routes/_layout/submissions/$submissionId'
import { Route as LayoutResourcesResourceIdRouteImport } from './routes/_layout/resources/$resourceId'

const WechatCallbackRoute = WechatCallbackRouteImport.update({
  id: '/wechat-callback',
  path: '/wechat-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFavoritesRoute = LayoutFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubmissionsIndexRoute = LayoutSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResourcesIndexRoute = LayoutResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubmissionsNewRoute = LayoutSubmissionsNewRouteImport.update({
  id: '/submissions/new',
  path: '/submissions/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubmissionsSubmissionIdRoute =
  LayoutSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutResourcesResourceIdRoute =
  LayoutResourcesResourceIdRouteImport.update({
    id: '/resources/$resourceId',
    path: '/resources/$resourceId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/wechat-callback': typeof WechatCallbackRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/favorites': typeof LayoutFavoritesRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/resources/$resourceId': typeof LayoutResourcesResourceIdRoute
  '/submissions/$submissionId': typeof LayoutSubmissionsSubmissionIdRoute
  '/submissions/new': typeof LayoutSubmissionsNewRoute
  '/resources': typeof LayoutResourcesIndexRoute
  '/submissions': typeof LayoutSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/wechat-callback': typeof WechatCallbackRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/favorites': typeof LayoutFavoritesRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/resources/$resourceId': typeof LayoutResourcesResourceIdRoute
  '/submissions/$submissionId': typeof LayoutSubmissionsSubmissionIdRoute
  '/submissions/new': typeof LayoutSubmissionsNewRoute
  '/resources': typeof LayoutResourcesIndexRoute
  '/submissions': typeof LayoutSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/wechat-callback': typeof WechatCallbackRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/favorites': typeof LayoutFavoritesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/resources/$resourceId': typeof LayoutResourcesResourceIdRoute
  '/_layout/submissions/$submissionId': typeof LayoutSubmissionsSubmissionIdRoute
  '/_layout/submissions/new': typeof LayoutSubmissionsNewRoute
  '/_layout/resources/': typeof LayoutResourcesIndexRoute
  '/_layout/submissions/': typeof LayoutSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/wechat-callback'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/items'
    | '/settings'
    | '/resources/$resourceId'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/resources'
    | '/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/wechat-callback'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/items'
    | '/settings'
    | '/resources/$resourceId'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/resources'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/wechat-callback'
    | '/_layout/admin'
    | '/_layout/dashboard'
    | '/_layout/favorites'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/resources/$resourceId'
    | '/_layout/submissions/$submissionId'
    | '/_layout/submissions/new'
    | '/_layout/resources/'
    | '/_layout/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WechatCallbackRoute: typeof WechatCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wechat-callback': {
      id: '/wechat-callback'
      path: '/wechat-callback'
      fullPath: '/wechat-callback'
      preLoaderRoute: typeof WechatCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/favorites': {
      id: '/_layout/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof LayoutFavoritesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/submissions/': {
      id: '/_layout/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof LayoutSubmissionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources/': {
      id: '/_layout/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof LayoutResourcesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/submissions/new': {
      id: '/_layout/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof LayoutSubmissionsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/submissions/$submissionId': {
      id: '/_layout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof LayoutSubmissionsSubmissionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources/$resourceId': {
      id: '/_layout/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof LayoutResourcesResourceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutFavoritesRoute: typeof LayoutFavoritesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutResourcesResourceIdRoute: typeof LayoutResourcesResourceIdRoute
  LayoutSubmissionsSubmissionIdRoute: typeof LayoutSubmissionsSubmissionIdRoute
  LayoutSubmissionsNewRoute: typeof LayoutSubmissionsNewRoute
  LayoutResourcesIndexRoute: typeof LayoutResourcesIndexRoute
  LayoutSubmissionsIndexRoute: typeof LayoutSubmissionsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutFavoritesRoute: LayoutFavoritesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutResourcesResourceIdRoute: LayoutResourcesResourceIdRoute,
  LayoutSubmissionsSubmissionIdRoute: LayoutSubmissionsSubmissionIdRoute,
  LayoutSubmissionsNewRoute: LayoutSubmissionsNewRoute,
  LayoutResourcesIndexRoute: LayoutResourcesIndexRoute,
  LayoutSubmissionsIndexRoute: LayoutSubmissionsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WechatCallbackRoute: WechatCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
